### ISSUE TITLE
Show Findr version in frontend

### ISSUE THREAD

**Issue by Event4-you** [surcoufx83/sysHUB-Findr#43]
The current version should be displayed on the frontend page.

**Comment by surcoufx83** [comment]
Hi @Event4-you 

which version would you like to see? The Findr version or the sysHUB Server version the backend is running on?

**Comment by Event4-you** [comment]
Findr Version

**Comment by surcoufx83** [comment]
Is added to the dropdown menu and will be available from the next beta version.

![image](https://github.com/surcoufx83/sysHUB-Findr/assets/1303974/1a367ba7-6333-4852-abc1-bf65aafe8b05)
